# Generated by Django 6.0 on 2025-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('contact', models.CharField(help_text='Телефон/WhatsApp', max_length=255)),
                ('source_type', models.CharField(choices=[('hotel', 'Отель'), ('rental', 'Прокат'), ('taxi', 'Такси'), ('site', 'Сайт'), ('other', 'Другое')], max_length=32)),
                ('source_text', models.CharField(blank=True, max_length=255)),
                ('needs', models.JSONField(default=list, help_text='Список нужд (массив значений Need)')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('offer', 'Офер'), ('booked', 'Забронировано'), ('canceled', 'Отменён'), ('no_response', 'Нет ответа')], default='new', max_length=32)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
