# Generated by Django 6.0 on 2025-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('instructor', 'Инструктор'), ('rental', 'Прокат'), ('hotel', 'Отель'), ('taxi', 'Такси'), ('nanny', 'Няня'), ('spa', 'SPA'), ('other', 'Другое')], max_length=32)),
                ('name', models.CharField(max_length=255, verbose_name='Название/ФИО')),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('whatsapp', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Курорт/Регион')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'На паузе')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
