# Generated by Django 6.0 on 2025-12-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждена'), ('completed', 'Выполнена'), ('canceled', 'Отменена'), ('no_show', 'No-show')], default='draft', max_length=16)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('instructor', 'Инструктор'), ('rental', 'Прокат'), ('taxi', 'Такси'), ('nanny', 'Няня'), ('spa', 'SPA'), ('other', 'Другое')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('guest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, help_text='Наша комиссия', max_digits=12, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner')),
            ],
        ),
    ]
